/**
 * Country list with ISO 3166-1 alpha-2 codes and Japanese names
 * Including all flags from assets/images/flags
 */

export interface Country {
  code: string;
  nameJa: string;
  nameEn: string;
}

export const COUNTRIES: Country[] = [
  // Major snowboarding countries (Priority)
  { code: 'JP', nameJa: '日本', nameEn: 'Japan' },
  { code: 'US', nameJa: 'アメリカ', nameEn: 'United States' },
  { code: 'CA', nameJa: 'カナダ', nameEn: 'Canada' },
  { code: 'AU', nameJa: 'オーストラリア', nameEn: 'Australia' },
  { code: 'NZ', nameJa: 'ニュージーランド', nameEn: 'New Zealand' },
  { code: 'FR', nameJa: 'フランス', nameEn: 'France' },
  { code: 'CH', nameJa: 'スイス', nameEn: 'Switzerland' },
  { code: 'AT', nameJa: 'オーストリア', nameEn: 'Austria' },
  { code: 'IT', nameJa: 'イタリア', nameEn: 'Italy' },
  { code: 'DE', nameJa: 'ドイツ', nameEn: 'Germany' },
  { code: 'CN', nameJa: '中国', nameEn: 'China' },
  { code: 'KR', nameJa: '韓国', nameEn: 'South Korea' },

  // All other countries (Alphabetical by code)
  { code: 'AD', nameJa: 'アンドラ', nameEn: 'Andorra' },
  { code: 'AE', nameJa: 'アラブ首長国連邦', nameEn: 'United Arab Emirates' },
  { code: 'AF', nameJa: 'アフガニスタン', nameEn: 'Afghanistan' },
  { code: 'AG', nameJa: 'アンティグア・バーブーダ', nameEn: 'Antigua and Barbuda' },
  { code: 'AI', nameJa: 'アンギラ', nameEn: 'Anguilla' },
  { code: 'AL', nameJa: 'アルバニア', nameEn: 'Albania' },
  { code: 'AM', nameJa: 'アルメニア', nameEn: 'Armenia' },
  { code: 'AO', nameJa: 'アンゴラ', nameEn: 'Angola' },
  { code: 'AQ', nameJa: '南極', nameEn: 'Antarctica' },
  { code: 'AR', nameJa: 'アルゼンチン', nameEn: 'Argentina' },
  { code: 'AS', nameJa: 'アメリカ領サモア', nameEn: 'American Samoa' },
  { code: 'AW', nameJa: 'アルバ', nameEn: 'Aruba' },
  { code: 'AX', nameJa: 'オーランド諸島', nameEn: 'Åland Islands' },
  { code: 'AZ', nameJa: 'アゼルバイジャン', nameEn: 'Azerbaijan' },
  { code: 'BA', nameJa: 'ボスニア・ヘルツェゴビナ', nameEn: 'Bosnia and Herzegovina' },
  { code: 'BB', nameJa: 'バルバドス', nameEn: 'Barbados' },
  { code: 'BD', nameJa: 'バングラデシュ', nameEn: 'Bangladesh' },
  { code: 'BE', nameJa: 'ベルギー', nameEn: 'Belgium' },
  { code: 'BF', nameJa: 'ブルキナファソ', nameEn: 'Burkina Faso' },
  { code: 'BG', nameJa: 'ブルガリア', nameEn: 'Bulgaria' },
  { code: 'BH', nameJa: 'バーレーン', nameEn: 'Bahrain' },
  { code: 'BI', nameJa: 'ブルンジ', nameEn: 'Burundi' },
  { code: 'BJ', nameJa: 'ベナン', nameEn: 'Benin' },
  { code: 'BL', nameJa: 'サン・バルテルミー', nameEn: 'Saint Barthélemy' },
  { code: 'BM', nameJa: 'バミューダ', nameEn: 'Bermuda' },
  { code: 'BN', nameJa: 'ブルネイ', nameEn: 'Brunei Darussalam' },
  { code: 'BO', nameJa: 'ボリビア', nameEn: 'Bolivia' },
  { code: 'BQ', nameJa: 'ボ奈・シント・ユースタティウス・サバ', nameEn: 'Bonaire, Sint Eustatius and Saba' },
  { code: 'BR', nameJa: 'ブラジル', nameEn: 'Brazil' },
  { code: 'BS', nameJa: 'バハマ', nameEn: 'Bahamas' },
  { code: 'BT', nameJa: 'ブータン', nameEn: 'Bhutan' },
  { code: 'BV', nameJa: 'ブーベ島', nameEn: 'Bouvet Island' },
  { code: 'BW', nameJa: 'ボツワナ', nameEn: 'Botswana' },
  { code: 'BY', nameJa: 'ベラルーシ', nameEn: 'Belarus' },
  { code: 'BZ', nameJa: 'ベリーズ', nameEn: 'Belize' },
  { code: 'CC', nameJa: 'ココス（キーリング）諸島', nameEn: 'Cocos (Keeling) Islands' },
  { code: 'CD', nameJa: 'コンゴ民主共和国', nameEn: 'Congo (Democratic Republic of the)' },
  { code: 'CF', nameJa: '中央アフリカ共和国', nameEn: 'Central African Republic' },
  { code: 'CG', nameJa: 'コンゴ共和国', nameEn: 'Congo' },
  { code: 'CI', nameJa: 'コートジボワール', nameEn: 'Côte d\'Ivoire' },
  { code: 'CK', nameJa: 'クック諸島', nameEn: 'Cook Islands' },
  { code: 'CL', nameJa: 'チリ', nameEn: 'Chile' },
  { code: 'CM', nameJa: 'カメルーン', nameEn: 'Cameroon' },
  { code: 'CO', nameJa: 'コロンビア', nameEn: 'Colombia' },
  { code: 'CR', nameJa: 'コスタリカ', nameEn: 'Costa Rica' },
  { code: 'CU', nameJa: 'キューバ', nameEn: 'Cuba' },
  { code: 'CV', nameJa: 'カーボベルデ', nameEn: 'Cabo Verde' },
  { code: 'CW', nameJa: 'キュラソー', nameEn: 'Curaçao' },
  { code: 'CX', nameJa: 'クリスマス島', nameEn: 'Christmas Island' },
  { code: 'CY', nameJa: 'キプロス', nameEn: 'Cyprus' },
  { code: 'CZ', nameJa: 'チェコ', nameEn: 'Czechia' },
  { code: 'DJ', nameJa: 'ジブチ', nameEn: 'Djibouti' },
  { code: 'DK', nameJa: 'デンマーク', nameEn: 'Denmark' },
  { code: 'DM', nameJa: 'ドミニカ国', nameEn: 'Dominica' },
  { code: 'DO', nameJa: 'ドミニカ共和国', nameEn: 'Dominican Republic' },
  { code: 'DZ', nameJa: 'アルジェリア', nameEn: 'Algeria' },
  { code: 'EC', nameJa: 'エクアドル', nameEn: 'Ecuador' },
  { code: 'EE', nameJa: 'エストニア', nameEn: 'Estonia' },
  { code: 'EG', nameJa: 'エジプト', nameEn: 'Egypt' },
  { code: 'EH', nameJa: '西サハラ', nameEn: 'Western Sahara' },
  { code: 'ER', nameJa: 'エリトリア', nameEn: 'Eritrea' },
  { code: 'ES', nameJa: 'スペイン', nameEn: 'Spain' },
  { code: 'ET', nameJa: 'エチオピア', nameEn: 'Ethiopia' },
  { code: 'FI', nameJa: 'フィンランド', nameEn: 'Finland' },
  { code: 'FJ', nameJa: 'フィジー', nameEn: 'Fiji' },
  { code: 'FK', nameJa: 'フォークランド諸島', nameEn: 'Falkland Islands' },
  { code: 'FM', nameJa: 'ミクロネシア', nameEn: 'Micronesia' },
  { code: 'FO', nameJa: 'フェロー諸島', nameEn: 'Faroe Islands' },
  { code: 'GA', nameJa: 'ガボン', nameEn: 'Gabon' },
  { code: 'GB', nameJa: 'イギリス', nameEn: 'United Kingdom' },
  { code: 'GB-ENG', nameJa: 'イングランド', nameEn: 'England' },
  { code: 'GB-NIR', nameJa: '北アイルランド', nameEn: 'Northern Ireland' },
  { code: 'GB-SCT', nameJa: 'スコットランド', nameEn: 'Scotland' },
  { code: 'GB-WLS', nameJa: 'ウェールズ', nameEn: 'Wales' },
  { code: 'GD', nameJa: 'グレナダ', nameEn: 'Grenada' },
  { code: 'GE', nameJa: 'ジョージア', nameEn: 'Georgia' },
  { code: 'GF', nameJa: 'フランス領ギアナ', nameEn: 'French Guiana' },
  { code: 'GG', nameJa: 'ガーンジー', nameEn: 'Guernsey' },
  { code: 'GH', nameJa: 'ガーナ', nameEn: 'Ghana' },
  { code: 'GI', nameJa: 'ジブラルタル', nameEn: 'Gibraltar' },
  { code: 'GL', nameJa: 'グリーンランド', nameEn: 'Greenland' },
  { code: 'GM', nameJa: 'ガンビア', nameEn: 'Gambia' },
  { code: 'GN', nameJa: 'ギニア', nameEn: 'Guinea' },
  { code: 'GP', nameJa: 'グアドループ', nameEn: 'Guadeloupe' },
  { code: 'GQ', nameJa: '赤道ギニア', nameEn: 'Equatorial Guinea' },
  { code: 'GR', nameJa: 'ギリシャ', nameEn: 'Greece' },
  { code: 'GS', nameJa: 'サウスジョージア・サウスサンドウィッチ諸島', nameEn: 'South Georgia and the South Sandwich Islands' },
  { code: 'GT', nameJa: 'グアテマラ', nameEn: 'Guatemala' },
  { code: 'GU', nameJa: 'グアム', nameEn: 'Guam' },
  { code: 'GW', nameJa: 'ギニアビサウ', nameEn: 'Guinea-Bissau' },
  { code: 'GY', nameJa: 'ガイアナ', nameEn: 'Guyana' },
  { code: 'HK', nameJa: '香港', nameEn: 'Hong Kong' },
  { code: 'HM', nameJa: 'ハード島・マクドナルド諸島', nameEn: 'Heard Island and McDonald Islands' },
  { code: 'HN', nameJa: 'ホンジュラス', nameEn: 'Honduras' },
  { code: 'HR', nameJa: 'クロアチア', nameEn: 'Croatia' },
  { code: 'HT', nameJa: 'ハイチ', nameEn: 'Haiti' },
  { code: 'HU', nameJa: 'ハンガリー', nameEn: 'Hungary' },
  { code: 'ID', nameJa: 'インドネシア', nameEn: 'Indonesia' },
  { code: 'IE', nameJa: 'アイルランド', nameEn: 'Ireland' },
  { code: 'IL', nameJa: 'イスラエル', nameEn: 'Israel' },
  { code: 'IM', nameJa: 'マン島', nameEn: 'Isle of Man' },
  { code: 'IN', nameJa: 'インド', nameEn: 'India' },
  { code: 'IO', nameJa: '英領インド洋地域', nameEn: 'British Indian Ocean Territory' },
  { code: 'IQ', nameJa: 'イラク', nameEn: 'Iraq' },
  { code: 'IR', nameJa: 'イラン', nameEn: 'Iran' },
  { code: 'IS', nameJa: 'アイスランド', nameEn: 'Iceland' },
  { code: 'JE', nameJa: 'ジャージー', nameEn: 'Jersey' },
  { code: 'JM', nameJa: 'ジャマイカ', nameEn: 'Jamaica' },
  { code: 'JO', nameJa: 'ヨルダン', nameEn: 'Jordan' },
  { code: 'KE', nameJa: 'ケニア', nameEn: 'Kenya' },
  { code: 'KG', nameJa: 'キルギス', nameEn: 'Kyrgyzstan' },
  { code: 'KH', nameJa: 'カンボジア', nameEn: 'Cambodia' },
  { code: 'KI', nameJa: 'キリバス', nameEn: 'Kiribati' },
  { code: 'KM', nameJa: 'コモロ', nameEn: 'Comoros' },
  { code: 'KN', nameJa: 'セントクリストファー・ネイビス', nameEn: 'Saint Kitts and Nevis' },
  { code: 'KP', nameJa: '北朝鮮', nameEn: 'North Korea' },
  { code: 'KW', nameJa: 'クウェート', nameEn: 'Kuwait' },
  { code: 'KY', nameJa: 'ケイマン諸島', nameEn: 'Cayman Islands' },
  { code: 'KZ', nameJa: 'カザフスタン', nameEn: 'Kazakhstan' },
  { code: 'LA', nameJa: 'ラオス', nameEn: 'Laos' },
  { code: 'LB', nameJa: 'レバノン', nameEn: 'Lebanon' },
  { code: 'LC', nameJa: 'セントルシア', nameEn: 'Saint Lucia' },
  { code: 'LI', nameJa: 'リヒテンシュタイン', nameEn: 'Liechtenstein' },
  { code: 'LK', nameJa: 'スリランカ', nameEn: 'Sri Lanka' },
  { code: 'LR', nameJa: 'リベリア', nameEn: 'Liberia' },
  { code: 'LS', nameJa: 'レソト', nameEn: 'Lesotho' },
  { code: 'LT', nameJa: 'リトアニア', nameEn: 'Lithuania' },
  { code: 'LU', nameJa: 'ルクセンブルク', nameEn: 'Luxembourg' },
  { code: 'LV', nameJa: 'ラトビア', nameEn: 'Latvia' },
  { code: 'LY', nameJa: 'リビア', nameEn: 'Libya' },
  { code: 'MA', nameJa: 'モロッコ', nameEn: 'Morocco' },
  { code: 'MC', nameJa: 'モナコ', nameEn: 'Monaco' },
  { code: 'MD', nameJa: 'モルドバ', nameEn: 'Moldova' },
  { code: 'ME', nameJa: 'モンテネグロ', nameEn: 'Montenegro' },
  { code: 'MF', nameJa: 'サン・マルタン', nameEn: 'Saint Martin' },
  { code: 'MG', nameJa: 'マダガスカル', nameEn: 'Madagascar' },
  { code: 'MH', nameJa: 'マーシャル諸島', nameEn: 'Marshall Islands' },
  { code: 'MK', nameJa: '北マケドニア', nameEn: 'North Macedonia' },
  { code: 'ML', nameJa: 'マリ', nameEn: 'Mali' },
  { code: 'MM', nameJa: 'ミャンマー', nameEn: 'Myanmar' },
  { code: 'MN', nameJa: 'モンゴル', nameEn: 'Mongolia' },
  { code: 'MO', nameJa: 'マカオ', nameEn: 'Macao' },
  { code: 'MP', nameJa: '北マリアナ諸島', nameEn: 'Northern Mariana Islands' },
  { code: 'MQ', nameJa: 'マルティニーク', nameEn: 'Martinique' },
  { code: 'MR', nameJa: 'モーリタニア', nameEn: 'Mauritania' },
  { code: 'MS', nameJa: 'モントセラト', nameEn: 'Montserrat' },
  { code: 'MT', nameJa: 'マルタ', nameEn: 'Malta' },
  { code: 'MU', nameJa: 'モーリシャス', nameEn: 'Mauritius' },
  { code: 'MV', nameJa: 'モルディブ', nameEn: 'Maldives' },
  { code: 'MW', nameJa: 'マラウイ', nameEn: 'Malawi' },
  { code: 'MX', nameJa: 'メキシコ', nameEn: 'Mexico' },
  { code: 'MY', nameJa: 'マレーシア', nameEn: 'Malaysia' },
  { code: 'MZ', nameJa: 'モザンビーク', nameEn: 'Mozambique' },
  { code: 'NA', nameJa: 'ナミビア', nameEn: 'Namibia' },
  { code: 'NC', nameJa: 'ニューカレドニア', nameEn: 'New Caledonia' },
  { code: 'NE', nameJa: 'ニジェール', nameEn: 'Niger' },
  { code: 'NF', nameJa: 'ノーフォーク島', nameEn: 'Norfolk Island' },
  { code: 'NG', nameJa: 'ナイジェリア', nameEn: 'Nigeria' },
  { code: 'NI', nameJa: 'ニカラグア', nameEn: 'Nicaragua' },
  { code: 'NL', nameJa: 'オランダ', nameEn: 'Netherlands' },
  { code: 'NO', nameJa: 'ノルウェー', nameEn: 'Norway' },
  { code: 'NP', nameJa: 'ネパール', nameEn: 'Nepal' },
  { code: 'NR', nameJa: 'ナウル', nameEn: 'Nauru' },
  { code: 'NU', nameJa: 'ニウエ', nameEn: 'Niue' },
  { code: 'OM', nameJa: 'オマーン', nameEn: 'Oman' },
  { code: 'PA', nameJa: 'パナマ', nameEn: 'Panama' },
  { code: 'PE', nameJa: 'ペルー', nameEn: 'Peru' },
  { code: 'PF', nameJa: 'フランス領ポリネシア', nameEn: 'French Polynesia' },
  { code: 'PG', nameJa: 'パプアニューギニア', nameEn: 'Papua New Guinea' },
  { code: 'PH', nameJa: 'フィリピン', nameEn: 'Philippines' },
  { code: 'PK', nameJa: 'パキスタン', nameEn: 'Pakistan' },
  { code: 'PL', nameJa: 'ポーランド', nameEn: 'Poland' },
  { code: 'PM', nameJa: 'サンピエール・ミクロン', nameEn: 'Saint Pierre and Miquelon' },
  { code: 'PN', nameJa: 'ピトケアン', nameEn: 'Pitcairn' },
  { code: 'PR', nameJa: 'プエルトリコ', nameEn: 'Puerto Rico' },
  { code: 'PS', nameJa: 'パレスチナ', nameEn: 'Palestine' },
  { code: 'PT', nameJa: 'ポルトガル', nameEn: 'Portugal' },
  { code: 'PW', nameJa: 'パラオ', nameEn: 'Palau' },
  { code: 'PY', nameJa: 'パラグアイ', nameEn: 'Paraguay' },
  { code: 'QA', nameJa: 'カタール', nameEn: 'Qatar' },
  { code: 'RE', nameJa: 'レユニオン', nameEn: 'Réunion' },
  { code: 'RO', nameJa: 'ルーマニア', nameEn: 'Romania' },
  { code: 'RS', nameJa: 'セルビア', nameEn: 'Serbia' },
  { code: 'RU', nameJa: 'ロシア', nameEn: 'Russia' },
  { code: 'RW', nameJa: 'ルワンダ', nameEn: 'Rwanda' },
  { code: 'SA', nameJa: 'サウジアラビア', nameEn: 'Saudi Arabia' },
  { code: 'SB', nameJa: 'ソロモン諸島', nameEn: 'Solomon Islands' },
  { code: 'SC', nameJa: 'セーシェル', nameEn: 'Seychelles' },
  { code: 'SD', nameJa: 'スーダン', nameEn: 'Sudan' },
  { code: 'SE', nameJa: 'スウェーデン', nameEn: 'Sweden' },
  { code: 'SG', nameJa: 'シンガポール', nameEn: 'Singapore' },
  { code: 'SH', nameJa: 'セントヘレナ', nameEn: 'Saint Helena' },
  { code: 'SI', nameJa: 'スロベニア', nameEn: 'Slovenia' },
  { code: 'SJ', nameJa: 'スヴァールバル諸島・ヤンマイエン島', nameEn: 'Svalbard and Jan Mayen' },
  { code: 'SK', nameJa: 'スロバキア', nameEn: 'Slovakia' },
  { code: 'SL', nameJa: 'シエラレオネ', nameEn: 'Sierra Leone' },
  { code: 'SM', nameJa: 'サンマリノ', nameEn: 'San Marino' },
  { code: 'SN', nameJa: 'セネガル', nameEn: 'Senegal' },
  { code: 'SO', nameJa: 'ソマリア', nameEn: 'Somalia' },
  { code: 'SR', nameJa: 'スリナム', nameEn: 'Suriname' },
  { code: 'SS', nameJa: '南スーダン', nameEn: 'South Sudan' },
  { code: 'ST', nameJa: 'サントメ・プリンシペ', nameEn: 'Sao Tome and Principe' },
  { code: 'SV', nameJa: 'エルサルバドル', nameEn: 'El Salvador' },
  { code: 'SX', nameJa: 'シント・マールテン', nameEn: 'Sint Maarten' },
  { code: 'SY', nameJa: 'シリア', nameEn: 'Syria' },
  { code: 'SZ', nameJa: 'エスワティニ', nameEn: 'Eswatini' },
  { code: 'TC', nameJa: 'タークス・カイコス諸島', nameEn: 'Turks and Caicos Islands' },
  { code: 'TD', nameJa: 'チャド', nameEn: 'Chad' },
  { code: 'TF', nameJa: 'フランス領南方・南極地域', nameEn: 'French Southern Territories' },
  { code: 'TG', nameJa: 'トーゴ', nameEn: 'Togo' },
  { code: 'TH', nameJa: 'タイ', nameEn: 'Thailand' },
  { code: 'TJ', nameJa: 'タジキスタン', nameEn: 'Tajikistan' },
  { code: 'TK', nameJa: 'トケラウ', nameEn: 'Tokelau' },
  { code: 'TL', nameJa: '東ティモール', nameEn: 'Timor-Leste' },
  { code: 'TM', nameJa: 'トルクメニスタン', nameEn: 'Turkmenistan' },
  { code: 'TN', nameJa: 'チュニジア', nameEn: 'Tunisia' },
  { code: 'TO', nameJa: 'トンガ', nameEn: 'Tonga' },
  { code: 'TR', nameJa: 'トルコ', nameEn: 'Turkey' },
  { code: 'TT', nameJa: 'トリニダード・トバゴ', nameEn: 'Trinidad and Tobago' },
  { code: 'TV', nameJa: 'ツバル', nameEn: 'Tuvalu' },
  { code: 'TW', nameJa: '台湾', nameEn: 'Taiwan' },
  { code: 'TZ', nameJa: 'タンザニア', nameEn: 'Tanzania' },
  { code: 'UA', nameJa: 'ウクライナ', nameEn: 'Ukraine' },
  { code: 'UG', nameJa: 'ウガンダ', nameEn: 'Uganda' },
  { code: 'UM', nameJa: '合衆国領有小離島', nameEn: 'United States Minor Outlying Islands' },
  { code: 'UY', nameJa: 'ウルグアイ', nameEn: 'Uruguay' },
  { code: 'UZ', nameJa: 'ウズベキスタン', nameEn: 'Uzbekistan' },
  { code: 'VA', nameJa: 'バチカン', nameEn: 'Holy See' },
  { code: 'VC', nameJa: 'セントビンセント・グレナディーン', nameEn: 'Saint Vincent and the Grenadines' },
  { code: 'VE', nameJa: 'ベネズエラ', nameEn: 'Venezuela' },
  { code: 'VG', nameJa: 'イギリス領ヴァージン諸島', nameEn: 'Virgin Islands (British)' },
  { code: 'VI', nameJa: 'アメリカ領ヴァージン諸島', nameEn: 'Virgin Islands (U.S.)' },
  { code: 'VN', nameJa: 'ベトナム', nameEn: 'Vietnam' },
  { code: 'VU', nameJa: 'バヌアツ', nameEn: 'Vanuatu' },
  { code: 'WF', nameJa: 'ウォリス・フツナ', nameEn: 'Wallis and Futuna' },
  { code: 'WS', nameJa: 'サモア', nameEn: 'Samoa' },
  { code: 'XK', nameJa: 'コソボ', nameEn: 'Kosovo' },
  { code: 'YE', nameJa: 'イエメン', nameEn: 'Yemen' },
  { code: 'YT', nameJa: 'マヨット', nameEn: 'Mayotte' },
  { code: 'ZA', nameJa: '南アフリカ', nameEn: 'South Africa' },
  { code: 'ZM', nameJa: 'ザンビア', nameEn: 'Zambia' },
  { code: 'ZW', nameJa: 'ジンバブエ', nameEn: 'Zimbabwe' },
];

// Remove duplicates based on code
const uniqueCountriesMap = new Map();
COUNTRIES.forEach(c => uniqueCountriesMap.set(c.code, c));
export const UNIQUE_COUNTRIES = Array.from(uniqueCountriesMap.values()) as Country[];

/**
 * Flag image mappings
 * React Native requires static paths for require()
 */
const FLAG_IMAGES: Record<string, any> = {
  // Lowercase keys used
  ad: require('../../assets/images/flags/ad.png'),
  ae: require('../../assets/images/flags/ae.png'),
  af: require('../../assets/images/flags/af.png'),
  ag: require('../../assets/images/flags/ag.png'),
  ai: require('../../assets/images/flags/ai.png'),
  al: require('../../assets/images/flags/al.png'),
  am: require('../../assets/images/flags/am.png'),
  ao: require('../../assets/images/flags/ao.png'),
  aq: require('../../assets/images/flags/aq.png'),
  ar: require('../../assets/images/flags/ar.png'),
  as: require('../../assets/images/flags/as.png'),
  at: require('../../assets/images/flags/at.png'),
  au: require('../../assets/images/flags/au.png'),
  aw: require('../../assets/images/flags/aw.png'),
  ax: require('../../assets/images/flags/ax.png'),
  az: require('../../assets/images/flags/az.png'),
  ba: require('../../assets/images/flags/ba.png'),
  bb: require('../../assets/images/flags/bb.png'),
  bd: require('../../assets/images/flags/bd.png'),
  be: require('../../assets/images/flags/be.png'),
  bf: require('../../assets/images/flags/bf.png'),
  bg: require('../../assets/images/flags/bg.png'),
  bh: require('../../assets/images/flags/bh.png'),
  bi: require('../../assets/images/flags/bi.png'),
  bj: require('../../assets/images/flags/bj.png'),
  bl: require('../../assets/images/flags/bl.png'),
  bm: require('../../assets/images/flags/bm.png'),
  bn: require('../../assets/images/flags/bn.png'),
  bo: require('../../assets/images/flags/bo.png'),
  bq: require('../../assets/images/flags/bq.png'),
  br: require('../../assets/images/flags/br.png'),
  bs: require('../../assets/images/flags/bs.png'),
  bt: require('../../assets/images/flags/bt.png'),
  bv: require('../../assets/images/flags/bv.png'),
  bw: require('../../assets/images/flags/bw.png'),
  by: require('../../assets/images/flags/by.png'),
  bz: require('../../assets/images/flags/bz.png'),
  ca: require('../../assets/images/flags/ca.png'),
  cc: require('../../assets/images/flags/cc.png'),
  cd: require('../../assets/images/flags/cd.png'),
  cf: require('../../assets/images/flags/cf.png'),
  cg: require('../../assets/images/flags/cg.png'),
  ch: require('../../assets/images/flags/ch.png'),
  ci: require('../../assets/images/flags/ci.png'),
  ck: require('../../assets/images/flags/ck.png'),
  cl: require('../../assets/images/flags/cl.png'),
  cm: require('../../assets/images/flags/cm.png'),
  cn: require('../../assets/images/flags/cn.png'),
  co: require('../../assets/images/flags/co.png'),
  cr: require('../../assets/images/flags/cr.png'),
  cu: require('../../assets/images/flags/cu.png'),
  cv: require('../../assets/images/flags/cv.png'),
  cw: require('../../assets/images/flags/cw.png'),
  cx: require('../../assets/images/flags/cx.png'),
  cy: require('../../assets/images/flags/cy.png'),
  cz: require('../../assets/images/flags/cz.png'),
  de: require('../../assets/images/flags/de.png'),
  dj: require('../../assets/images/flags/dj.png'),
  dk: require('../../assets/images/flags/dk.png'),
  dm: require('../../assets/images/flags/dm.png'),
  do: require('../../assets/images/flags/do.png'),
  dz: require('../../assets/images/flags/dz.png'),
  ec: require('../../assets/images/flags/ec.png'),
  ee: require('../../assets/images/flags/ee.png'),
  eg: require('../../assets/images/flags/eg.png'),
  eh: require('../../assets/images/flags/eh.png'),
  er: require('../../assets/images/flags/er.png'),
  es: require('../../assets/images/flags/es.png'),
  et: require('../../assets/images/flags/et.png'),
  fi: require('../../assets/images/flags/fi.png'),
  fj: require('../../assets/images/flags/fj.png'),
  fk: require('../../assets/images/flags/fk.png'),
  fm: require('../../assets/images/flags/fm.png'),
  fo: require('../../assets/images/flags/fo.png'),
  fr: require('../../assets/images/flags/fr.png'),
  ga: require('../../assets/images/flags/ga.png'),
  gb: require('../../assets/images/flags/gb.png'),
  'gb-eng': require('../../assets/images/flags/gb-eng.png'),
  'gb-nir': require('../../assets/images/flags/gb-nir.png'),
  'gb-sct': require('../../assets/images/flags/gb-sct.png'),
  'gb-wls': require('../../assets/images/flags/gb-wls.png'),
  gd: require('../../assets/images/flags/gd.png'),
  ge: require('../../assets/images/flags/ge.png'),
  gf: require('../../assets/images/flags/gf.png'),
  gg: require('../../assets/images/flags/gg.png'),
  gh: require('../../assets/images/flags/gh.png'),
  gi: require('../../assets/images/flags/gi.png'),
  gl: require('../../assets/images/flags/gl.png'),
  gm: require('../../assets/images/flags/gm.png'),
  gn: require('../../assets/images/flags/gn.png'),
  gp: require('../../assets/images/flags/gp.png'),
  gq: require('../../assets/images/flags/gq.png'),
  gr: require('../../assets/images/flags/gr.png'),
  gs: require('../../assets/images/flags/gs.png'),
  gt: require('../../assets/images/flags/gt.png'),
  gu: require('../../assets/images/flags/gu.png'),
  gw: require('../../assets/images/flags/gw.png'),
  gy: require('../../assets/images/flags/gy.png'),
  hk: require('../../assets/images/flags/hk.png'),
  hm: require('../../assets/images/flags/hm.png'),
  hn: require('../../assets/images/flags/hn.png'),
  hr: require('../../assets/images/flags/hr.png'),
  ht: require('../../assets/images/flags/ht.png'),
  hu: require('../../assets/images/flags/hu.png'),
  id: require('../../assets/images/flags/id.png'),
  ie: require('../../assets/images/flags/ie.png'),
  il: require('../../assets/images/flags/il.png'),
  im: require('../../assets/images/flags/im.png'),
  in: require('../../assets/images/flags/in.png'),
  io: require('../../assets/images/flags/io.png'),
  iq: require('../../assets/images/flags/iq.png'),
  ir: require('../../assets/images/flags/ir.png'),
  is: require('../../assets/images/flags/is.png'),
  it: require('../../assets/images/flags/it.png'),
  je: require('../../assets/images/flags/je.png'),
  jm: require('../../assets/images/flags/jm.png'),
  jo: require('../../assets/images/flags/jo.png'),
  jp: require('../../assets/images/flags/jp.png'),
  ke: require('../../assets/images/flags/ke.png'),
  kg: require('../../assets/images/flags/kg.png'),
  kh: require('../../assets/images/flags/kh.png'),
  ki: require('../../assets/images/flags/ki.png'),
  km: require('../../assets/images/flags/km.png'),
  kn: require('../../assets/images/flags/kn.png'),
  kp: require('../../assets/images/flags/kp.png'),
  kr: require('../../assets/images/flags/kr.png'),
  kw: require('../../assets/images/flags/kw.png'),
  ky: require('../../assets/images/flags/ky.png'),
  kz: require('../../assets/images/flags/kz.png'),
  la: require('../../assets/images/flags/la.png'),
  lb: require('../../assets/images/flags/lb.png'),
  lc: require('../../assets/images/flags/lc.png'),
  li: require('../../assets/images/flags/li.png'),
  lk: require('../../assets/images/flags/lk.png'),
  lr: require('../../assets/images/flags/lr.png'),
  ls: require('../../assets/images/flags/ls.png'),
  lt: require('../../assets/images/flags/lt.png'),
  lu: require('../../assets/images/flags/lu.png'),
  lv: require('../../assets/images/flags/lv.png'),
  ly: require('../../assets/images/flags/ly.png'),
  ma: require('../../assets/images/flags/ma.png'),
  mc: require('../../assets/images/flags/mc.png'),
  md: require('../../assets/images/flags/md.png'),
  me: require('../../assets/images/flags/me.png'),
  mf: require('../../assets/images/flags/mf.png'),
  mg: require('../../assets/images/flags/mg.png'),
  mh: require('../../assets/images/flags/mh.png'),
  mk: require('../../assets/images/flags/mk.png'),
  ml: require('../../assets/images/flags/ml.png'),
  mm: require('../../assets/images/flags/mm.png'),
  mn: require('../../assets/images/flags/mn.png'),
  mo: require('../../assets/images/flags/mo.png'),
  mp: require('../../assets/images/flags/mp.png'),
  mq: require('../../assets/images/flags/mq.png'),
  mr: require('../../assets/images/flags/mr.png'),
  ms: require('../../assets/images/flags/ms.png'),
  mt: require('../../assets/images/flags/mt.png'),
  mu: require('../../assets/images/flags/mu.png'),
  mv: require('../../assets/images/flags/mv.png'),
  mw: require('../../assets/images/flags/mw.png'),
  mx: require('../../assets/images/flags/mx.png'),
  my: require('../../assets/images/flags/my.png'),
  mz: require('../../assets/images/flags/mz.png'),
  na: require('../../assets/images/flags/na.png'),
  nc: require('../../assets/images/flags/nc.png'),
  ne: require('../../assets/images/flags/ne.png'),
  nf: require('../../assets/images/flags/nf.png'),
  ng: require('../../assets/images/flags/ng.png'),
  ni: require('../../assets/images/flags/ni.png'),
  nl: require('../../assets/images/flags/nl.png'),
  no: require('../../assets/images/flags/no.png'),
  np: require('../../assets/images/flags/np.png'),
  nr: require('../../assets/images/flags/nr.png'),
  nu: require('../../assets/images/flags/nu.png'),
  nz: require('../../assets/images/flags/nz.png'),
  om: require('../../assets/images/flags/om.png'),
  pa: require('../../assets/images/flags/pa.png'),
  pe: require('../../assets/images/flags/pe.png'),
  pf: require('../../assets/images/flags/pf.png'),
  pg: require('../../assets/images/flags/pg.png'),
  ph: require('../../assets/images/flags/ph.png'),
  pk: require('../../assets/images/flags/pk.png'),
  pl: require('../../assets/images/flags/pl.png'),
  pm: require('../../assets/images/flags/pm.png'),
  pn: require('../../assets/images/flags/pn.png'),
  pr: require('../../assets/images/flags/pr.png'),
  ps: require('../../assets/images/flags/ps.png'),
  pt: require('../../assets/images/flags/pt.png'),
  pw: require('../../assets/images/flags/pw.png'),
  py: require('../../assets/images/flags/py.png'),
  qa: require('../../assets/images/flags/qa.png'),
  re: require('../../assets/images/flags/re.png'),
  ro: require('../../assets/images/flags/ro.png'),
  rs: require('../../assets/images/flags/rs.png'),
  ru: require('../../assets/images/flags/ru.png'),
  rw: require('../../assets/images/flags/rw.png'),
  sa: require('../../assets/images/flags/sa.png'),
  sb: require('../../assets/images/flags/sb.png'),
  sc: require('../../assets/images/flags/sc.png'),
  sd: require('../../assets/images/flags/sd.png'),
  se: require('../../assets/images/flags/se.png'),
  sg: require('../../assets/images/flags/sg.png'),
  sh: require('../../assets/images/flags/sh.png'),
  si: require('../../assets/images/flags/si.png'),
  sj: require('../../assets/images/flags/sj.png'),
  sk: require('../../assets/images/flags/sk.png'),
  sl: require('../../assets/images/flags/sl.png'),
  sm: require('../../assets/images/flags/sm.png'),
  sn: require('../../assets/images/flags/sn.png'),
  so: require('../../assets/images/flags/so.png'),
  sr: require('../../assets/images/flags/sr.png'),
  ss: require('../../assets/images/flags/ss.png'),
  st: require('../../assets/images/flags/st.png'),
  sv: require('../../assets/images/flags/sv.png'),
  sx: require('../../assets/images/flags/sx.png'),
  sy: require('../../assets/images/flags/sy.png'),
  sz: require('../../assets/images/flags/sz.png'),
  tc: require('../../assets/images/flags/tc.png'),
  td: require('../../assets/images/flags/td.png'),
  tf: require('../../assets/images/flags/tf.png'),
  tg: require('../../assets/images/flags/tg.png'),
  th: require('../../assets/images/flags/th.png'),
  tj: require('../../assets/images/flags/tj.png'),
  tk: require('../../assets/images/flags/tk.png'),
  tl: require('../../assets/images/flags/tl.png'),
  tm: require('../../assets/images/flags/tm.png'),
  tn: require('../../assets/images/flags/tn.png'),
  to: require('../../assets/images/flags/to.png'),
  tr: require('../../assets/images/flags/tr.png'),
  tt: require('../../assets/images/flags/tt.png'),
  tv: require('../../assets/images/flags/tv.png'),
  tw: require('../../assets/images/flags/tw.png'),
  tz: require('../../assets/images/flags/tz.png'),
  ua: require('../../assets/images/flags/ua.png'),
  ug: require('../../assets/images/flags/ug.png'),
  um: require('../../assets/images/flags/um.png'),
  us: require('../../assets/images/flags/us.png'),
  uy: require('../../assets/images/flags/uy.png'),
  uz: require('../../assets/images/flags/uz.png'),
  va: require('../../assets/images/flags/va.png'),
  vc: require('../../assets/images/flags/vc.png'),
  ve: require('../../assets/images/flags/ve.png'),
  vg: require('../../assets/images/flags/vg.png'),
  vi: require('../../assets/images/flags/vi.png'),
  vn: require('../../assets/images/flags/vn.png'),
  vu: require('../../assets/images/flags/vu.png'),
  wf: require('../../assets/images/flags/wf.png'),
  ws: require('../../assets/images/flags/ws.png'),
  xk: require('../../assets/images/flags/xk.png'),
  ye: require('../../assets/images/flags/ye.png'),
  yt: require('../../assets/images/flags/yt.png'),
  za: require('../../assets/images/flags/za.png'),
  zm: require('../../assets/images/flags/zm.png'),
  zw: require('../../assets/images/flags/zw.png'),
};

/**
 * Get country flag image from country code
 */
export const getFlagSource = (countryCode: string) => {
  if (!countryCode) return FLAG_IMAGES.jp;
  const code = countryCode.toLowerCase();
  return FLAG_IMAGES[code] || FLAG_IMAGES.jp;
};
